---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: prometheus-am-executor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prometheus-am-executor
  name: prometheus-am-executor
  namespace: prometheus-am-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus-am-executor
  strategy: {}
  template:
    metadata:
      labels:
        run: prometheus-am-executor
    spec:
      containers:
      - image: ghcr.io/oxalide-mp-tech/prometheus-am-executor:master
        imagePullPolicy: Always
        name: prometheus-am-executor
        ports:
        - containerPort: 8080
          name: http
        command: ["/usr/local/go/bin/prometheus-am-executor", "-v", "/manifests-v1/purge-redis.sh"]
        resources: {}
        volumeMounts:
        - name: purge-key-without-ttl-job
          mountPath: ./manifests-v1
        livenessProbe:
          httpGet:
            path: /_health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /_health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: purge-key-without-ttl-job
          configMap:
            name: purge-key-without-ttl-job
            defaultMode: 0500
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: prometheus-am-executor
  name: prometheus-am-executor
  namespace: prometheus-am-executor
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    run: prometheus-am-executor
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: allow-create-job-redis-purge
  namespace: prometheus-am-executor
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - patch
  - delete
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: allow-default-to-purge-redis-keys
  namespace: prometheus-am-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-create-job-redis-purge
subjects:
- kind: ServiceAccount
  name: default
  namespace: prometheus-am-executor
