apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/oxalide-mp-tech/prometheus-am-executor
  newTag: master
resources:
- deployment.yaml

# declare ConfigMap from a ConfigMapGenerator
    # configfile is used as key
configMapGenerator:
- files:
  - configmap/purge-key-without-ttl-job.yaml
  - configmap/purge-redis.sh
  - configmap/redis-command.sh
  name: purge-key-without-ttl-job
  namespace: prometheus-am-executor
  options:
    disableNameSuffixHash: true
