apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/oxalide-mp-tech/prometheus-am-executor
  newTag: master
resources:
- deployment.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: purge-key-without-ttl-job
  namespace: prometheus-am-executor
  files:
    # configfile is used as key
    - configmap/purge-key-without-ttl-job.yaml
    - configmap/purge-redis.sh
    - configmap/redis-command.sh
