apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
images:
- name: ghcr.io/oxalide-mp-tech/prometheus-am-executor
  newTag: master

secretGenerator:
- name: slack-secrets
  namespace: prometheus-am-executor
  envs:
  - .env.secret
  options:
    disableNameSuffixHash: true
  type: Opaque

# configMapGenerator:
#   - name: config-example
#     env: config.properties

