apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/oxalide-mp-tech/prometheus-am-executor
  newTag: master

secretGenerator:
- envs:
  - .env.secret
  name: slack-secrets
  namespace: prometheus-am-executor
  options:
    disableNameSuffixHash: true
  type: Opaque
resources:
- ../../base
