apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: purge-key-without-ttl-job
  namespace: prometheus-am-executor
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      # - command:
      #   - /bin/sleep
      #   - "300"
      - command:
        - /bin/bash
        - -c
        - /scripts/redis-command.sh
        image: redis:7-bookworm
        imagePullPolicy: Always
        name: purge-key-without-ttl-job
        env:
        - name: CHANNEL_CI
          value: staging-k8s
        envFrom:
        - secretRef:
            name: slack-secrets
        resources: {}
        volumeMounts:
        - name: redis-purge-script
          mountPath: ./scripts
      restartPolicy: Never
      volumes:
        - name: redis-purge-script
          configMap:
            name: purge-key-without-ttl-job
            defaultMode: 0500
status: {}
